
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1.0']

    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # if you need redis
      # redis:
      #   image: redis
      #   ports:
      #   - 6379:6379
      #   options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - name: Rubocop
        run: rubocop
      # - name: Setup test database
      #   env:
      #     DATABASE_URL: postgres://postgres:@localhost:5432/test
      #     RAILS_ENV: test
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #   run: |
      #     bundle exec rails db:create
      #     bundle exec rails db:migrate
      #     RAILS_ENV=test bundle exec rake
      # - name: Run tests
      #   env:
      #     PGHOST: localhost
      #     POSTGRES_DB: rails_github_actions_test
      #     POSTGRES_USER: rails_github_actions
      #     POSTGRES_PASSWORD: postgres
      #     PGPORT: ${{ job.services.postgres.ports[5432] }}
      #     RAILS_ENV: test
      #   run: rspec

    
