name: RSpec

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.x

      - name: Install dependencies
        run: |
          sudo apt-get -yqq --mirror=http://archive.ubuntu.com/ubuntu install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Update package lists
        run: sudo apt-get update

      - name: Run RSpec tests
        run: bundle exec rspec