name: RSpec

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: bundle install

      - name: Update package lists
        run: sudo apt-get update

      - name: Run RSpec tests
        run: bundle exec rspec